#!/bin/bash
#
# Copyright 2014 Dean Okamura
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

SCRIPT=vmdk-disk

if [ "$1" = "" ] ; then
    DISK=/dev/sda
else
    DISK=$1
fi
if [ "$2" = "" ] ; then
    NAME=$(pwd)
    NAME=$(basename $NAME).vmdk
else
    NAME=$2
fi
COMMAND="./$SCRIPT $DISK $NAME"
zenity --question --title="$SCRIPT" --text="Continue with $COMMAND?"
if [ $? -eq 0 ] ; then
    sudo ./$SCRIPT $DISK $NAME
fi
