#!/bin/bash
#
# Copyright 2013 Dean Okamura
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

HOST_VMDK=libre

tasks()
{
    if [ -f /usr/bin/apt-get ] ; then
        apt-get install -y openssh-server
    elif [ -f /usr/bin/yum ] ; then
        yum install -y openssh-server
    else
        echo "TBD"
        return
    fi
    mkdir /vmdk
    mount /dev/sdb1 /vmdk
    if [ ! -f /vmdk/$HOST_VMDK/$HOST_VMDK.zip ] ; then
        echo "/vmdk/$HOST_VMDK/$HOST_VMDK.zip not found"
        return
    fi
    if [ ! -f /vmdk/$HOST_VMDK/vmdk-disk ] ; then
        echo "/vmdk/$HOST_VMDK/vmdk-disk not found"
        return
    fi
    cd /vmdk/$HOST_VMDK
    ./vmdk-disk
}

if [ ! "$(whoami)" = "root" ] ; then
    echo "Run $0 as root"
else
    tasks
fi

#
