#!/bin/bash
#
# Copyright 2013 Dean Okamura
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

disk()
{
    if [ "$1" = "" ] ; then
        TARGET=/dev/sda
    else
        TARGET=$1
    fi

    if [ ! "$(df | grep $TARGET)" = "" ] ; then
        echo "$TARGET is mounted"
        exit 1
    fi

    name=$(ls *.zip | sed -e 's#.zip$##')
    if [ ! -f $name.zip ] ; then
        echo "$name.zip not found"
        exit 1
    fi

    if [ ! -f /usr/bin/qemu-img ] ; then
        if [ -f /usr/bin/apt-get ] ; then
            sudo apt-get install -y qemu-kvm
        else
            sudo yum install -y qemu-kvm
        fi
    fi

    if [ ! -f /usr/bin/qemu-img ] ; then
        echo "/usr/bin/qemu-img not found"
        exit 1
    fi

    unzip $name.zip $name.vmdk
    if [ ! -f $name.vmdk ] ; then
        echo "$name.vmdk not found"
        exit 1
    fi

    echo "Image $name.vmdk to $TARGET"
    qemu-img convert $name.vmdk -O raw $TARGET

    echo "Remove $name.vmdk"
    rm -f $name.vmdk
}

case "$1" in
-t ) disk $2 ;;
* ) sudo $0 -t $* ;;
esac

#
